-- Generated by redesign/timezones/generate.mjs from tzdb's zone.tab, CLDR's
-- English city names and the country names of Database/Seed/Countries.sql.
-- Change the script and run it again rather than editing this file.
module TeamTavern.Shared.Timezones where

type Timezone =
    { city :: String
    , country :: String
    , name :: String
    }

allTimezones :: Array Timezone
allTimezones =
    [
        { name: "Asia/Kabul"
        , city: "Kabul"
        , country: "Afghanistan"
        },
        { name: "Europe/Mariehamn"
        , city: "Mariehamn"
        , country: "Åland Islands"
        },
        { name: "Europe/Tirane"
        , city: "Tirana"
        , country: "Albania"
        },
        { name: "Africa/Algiers"
        , city: "Algiers"
        , country: "Algeria"
        },
        { name: "Pacific/Pago_Pago"
        , city: "Pago Pago"
        , country: "American Samoa"
        },
        { name: "Europe/Andorra"
        , city: "Andorra"
        , country: "Andorra"
        },
        { name: "Africa/Luanda"
        , city: "Luanda"
        , country: "Angola"
        },
        { name: "America/Anguilla"
        , city: "Anguilla"
        , country: "Anguilla"
        },
        { name: "Antarctica/Casey"
        , city: "Casey Station"
        , country: "Antarctica"
        },
        { name: "Antarctica/Davis"
        , city: "Davis"
        , country: "Antarctica"
        },
        { name: "Antarctica/DumontDUrville"
        , city: "Dumont d’Urville Station"
        , country: "Antarctica"
        },
        { name: "Antarctica/Mawson"
        , city: "Mawson Station"
        , country: "Antarctica"
        },
        { name: "Antarctica/McMurdo"
        , city: "McMurdo Station"
        , country: "Antarctica"
        },
        { name: "Antarctica/Palmer"
        , city: "Palmer Land"
        , country: "Antarctica"
        },
        { name: "Antarctica/Rothera"
        , city: "Rothera Station"
        , country: "Antarctica"
        },
        { name: "Antarctica/Syowa"
        , city: "Showa Station"
        , country: "Antarctica"
        },
        { name: "Antarctica/Troll"
        , city: "Troll Station"
        , country: "Antarctica"
        },
        { name: "Antarctica/Vostok"
        , city: "Vostok Station"
        , country: "Antarctica"
        },
        { name: "America/Antigua"
        , city: "Antigua"
        , country: "Antigua and Barbuda"
        },
        { name: "America/Argentina/Buenos_Aires"
        , city: "Buenos Aires"
        , country: "Argentina"
        },
        { name: "America/Argentina/Catamarca"
        , city: "Catamarca"
        , country: "Argentina"
        },
        { name: "America/Argentina/Cordoba"
        , city: "Cordoba"
        , country: "Argentina"
        },
        { name: "America/Argentina/Jujuy"
        , city: "Jujuy"
        , country: "Argentina"
        },
        { name: "America/Argentina/La_Rioja"
        , city: "La Rioja"
        , country: "Argentina"
        },
        { name: "America/Argentina/Mendoza"
        , city: "Mendoza"
        , country: "Argentina"
        },
        { name: "America/Argentina/Rio_Gallegos"
        , city: "Río Gallegos"
        , country: "Argentina"
        },
        { name: "America/Argentina/Salta"
        , city: "Salta"
        , country: "Argentina"
        },
        { name: "America/Argentina/San_Juan"
        , city: "San Juan"
        , country: "Argentina"
        },
        { name: "America/Argentina/San_Luis"
        , city: "San Luis"
        , country: "Argentina"
        },
        { name: "America/Argentina/Tucuman"
        , city: "Tucumán"
        , country: "Argentina"
        },
        { name: "America/Argentina/Ushuaia"
        , city: "Ushuaia"
        , country: "Argentina"
        },
        { name: "Asia/Yerevan"
        , city: "Yerevan"
        , country: "Armenia"
        },
        { name: "America/Aruba"
        , city: "Aruba"
        , country: "Aruba"
        },
        { name: "Australia/Adelaide"
        , city: "Adelaide"
        , country: "Australia"
        },
        { name: "Australia/Brisbane"
        , city: "Brisbane"
        , country: "Australia"
        },
        { name: "Australia/Broken_Hill"
        , city: "Broken Hill"
        , country: "Australia"
        },
        { name: "Australia/Darwin"
        , city: "Darwin"
        , country: "Australia"
        },
        { name: "Australia/Eucla"
        , city: "Eucla"
        , country: "Australia"
        },
        { name: "Australia/Hobart"
        , city: "Hobart"
        , country: "Australia"
        },
        { name: "Australia/Lindeman"
        , city: "Lindeman"
        , country: "Australia"
        },
        { name: "Australia/Lord_Howe"
        , city: "Lord Howe Island"
        , country: "Australia"
        },
        { name: "Antarctica/Macquarie"
        , city: "Macquarie Island"
        , country: "Australia"
        },
        { name: "Australia/Melbourne"
        , city: "Melbourne"
        , country: "Australia"
        },
        { name: "Australia/Perth"
        , city: "Perth"
        , country: "Australia"
        },
        { name: "Australia/Sydney"
        , city: "Sydney"
        , country: "Australia"
        },
        { name: "Europe/Vienna"
        , city: "Vienna"
        , country: "Austria"
        },
        { name: "Asia/Baku"
        , city: "Baku"
        , country: "Azerbaijan"
        },
        { name: "America/Nassau"
        , city: "Nassau"
        , country: "Bahamas"
        },
        { name: "Asia/Bahrain"
        , city: "Bahrain"
        , country: "Bahrain"
        },
        { name: "Asia/Dhaka"
        , city: "Dhaka"
        , country: "Bangladesh"
        },
        { name: "America/Barbados"
        , city: "Barbados"
        , country: "Barbados"
        },
        { name: "Europe/Minsk"
        , city: "Minsk"
        , country: "Belarus"
        },
        { name: "Europe/Brussels"
        , city: "Brussels"
        , country: "Belgium"
        },
        { name: "America/Belize"
        , city: "Belize"
        , country: "Belize"
        },
        { name: "Africa/Porto-Novo"
        , city: "Porto-Novo"
        , country: "Benin"
        },
        { name: "Atlantic/Bermuda"
        , city: "Bermuda"
        , country: "Bermuda"
        },
        { name: "Asia/Thimphu"
        , city: "Thimphu"
        , country: "Bhutan"
        },
        { name: "America/La_Paz"
        , city: "La Paz"
        , country: "Bolivia"
        },
        { name: "America/Kralendijk"
        , city: "Kralendijk"
        , country: "Bonaire"
        },
        { name: "Europe/Sarajevo"
        , city: "Sarajevo"
        , country: "Bosnia and Herzegovina"
        },
        { name: "Africa/Gaborone"
        , city: "Gaborone"
        , country: "Botswana"
        },
        { name: "America/Araguaina"
        , city: "Araguaína"
        , country: "Brazil"
        },
        { name: "America/Bahia"
        , city: "Bahia"
        , country: "Brazil"
        },
        { name: "America/Belem"
        , city: "Belém"
        , country: "Brazil"
        },
        { name: "America/Boa_Vista"
        , city: "Boa Vista"
        , country: "Brazil"
        },
        { name: "America/Campo_Grande"
        , city: "Campo Grande"
        , country: "Brazil"
        },
        { name: "America/Cuiaba"
        , city: "Cuiabá"
        , country: "Brazil"
        },
        { name: "America/Eirunepe"
        , city: "Eirunepé"
        , country: "Brazil"
        },
        { name: "America/Noronha"
        , city: "Fernando de Noronha"
        , country: "Brazil"
        },
        { name: "America/Fortaleza"
        , city: "Fortaleza"
        , country: "Brazil"
        },
        { name: "America/Maceio"
        , city: "Maceió"
        , country: "Brazil"
        },
        { name: "America/Manaus"
        , city: "Manaus"
        , country: "Brazil"
        },
        { name: "America/Porto_Velho"
        , city: "Porto Velho"
        , country: "Brazil"
        },
        { name: "America/Recife"
        , city: "Recife"
        , country: "Brazil"
        },
        { name: "America/Rio_Branco"
        , city: "Rio Branco"
        , country: "Brazil"
        },
        { name: "America/Santarem"
        , city: "Santarém"
        , country: "Brazil"
        },
        { name: "America/Sao_Paulo"
        , city: "São Paulo"
        , country: "Brazil"
        },
        { name: "Indian/Chagos"
        , city: "Chagos Archipelago"
        , country: "British Indian Ocean Territory"
        },
        { name: "America/Tortola"
        , city: "Tortola"
        , country: "British Virgin Islands"
        },
        { name: "Asia/Brunei"
        , city: "Brunei"
        , country: "Brunei"
        },
        { name: "Europe/Sofia"
        , city: "Sofia"
        , country: "Bulgaria"
        },
        { name: "Africa/Ouagadougou"
        , city: "Ouagadougou"
        , country: "Burkina Faso"
        },
        { name: "Africa/Bujumbura"
        , city: "Bujumbura"
        , country: "Burundi"
        },
        { name: "Atlantic/Cape_Verde"
        , city: "Cape Verde"
        , country: "Cabo Verde"
        },
        { name: "Asia/Phnom_Penh"
        , city: "Phnom Penh"
        , country: "Cambodia"
        },
        { name: "Africa/Douala"
        , city: "Douala"
        , country: "Cameroon"
        },
        { name: "America/Atikokan"
        , city: "Atikokan"
        , country: "Canada"
        },
        { name: "America/Blanc-Sablon"
        , city: "Blanc-Sablon"
        , country: "Canada"
        },
        { name: "America/Cambridge_Bay"
        , city: "Cambridge Bay"
        , country: "Canada"
        },
        { name: "America/Creston"
        , city: "Creston"
        , country: "Canada"
        },
        { name: "America/Dawson"
        , city: "Dawson"
        , country: "Canada"
        },
        { name: "America/Dawson_Creek"
        , city: "Dawson Creek"
        , country: "Canada"
        },
        { name: "America/Edmonton"
        , city: "Edmonton"
        , country: "Canada"
        },
        { name: "America/Fort_Nelson"
        , city: "Fort Nelson"
        , country: "Canada"
        },
        { name: "America/Glace_Bay"
        , city: "Glace Bay"
        , country: "Canada"
        },
        { name: "America/Goose_Bay"
        , city: "Goose Bay"
        , country: "Canada"
        },
        { name: "America/Halifax"
        , city: "Halifax"
        , country: "Canada"
        },
        { name: "America/Inuvik"
        , city: "Inuvik"
        , country: "Canada"
        },
        { name: "America/Iqaluit"
        , city: "Iqaluit"
        , country: "Canada"
        },
        { name: "America/Moncton"
        , city: "Moncton"
        , country: "Canada"
        },
        { name: "America/Rankin_Inlet"
        , city: "Rankin Inlet"
        , country: "Canada"
        },
        { name: "America/Regina"
        , city: "Regina"
        , country: "Canada"
        },
        { name: "America/Resolute"
        , city: "Resolute"
        , country: "Canada"
        },
        { name: "America/St_Johns"
        , city: "St. John’s"
        , country: "Canada"
        },
        { name: "America/Swift_Current"
        , city: "Swift Current"
        , country: "Canada"
        },
        { name: "America/Toronto"
        , city: "Toronto"
        , country: "Canada"
        },
        { name: "America/Vancouver"
        , city: "Vancouver"
        , country: "Canada"
        },
        { name: "America/Whitehorse"
        , city: "Whitehorse"
        , country: "Canada"
        },
        { name: "America/Winnipeg"
        , city: "Winnipeg"
        , country: "Canada"
        },
        { name: "America/Cayman"
        , city: "Cayman"
        , country: "Cayman Islands"
        },
        { name: "Africa/Bangui"
        , city: "Bangui"
        , country: "Central African Republic"
        },
        { name: "Africa/Ndjamena"
        , city: "N’Djamena"
        , country: "Chad"
        },
        { name: "America/Coyhaique"
        , city: "Coyhaique"
        , country: "Chile"
        },
        { name: "Pacific/Easter"
        , city: "Easter Island"
        , country: "Chile"
        },
        { name: "America/Punta_Arenas"
        , city: "Punta Arenas"
        , country: "Chile"
        },
        { name: "America/Santiago"
        , city: "Santiago"
        , country: "Chile"
        },
        { name: "Asia/Shanghai"
        , city: "Shanghai"
        , country: "China"
        },
        { name: "Asia/Urumqi"
        , city: "Ürümqi"
        , country: "China"
        },
        { name: "Indian/Christmas"
        , city: "Christmas Island"
        , country: "Christmas Island"
        },
        { name: "Indian/Cocos"
        , city: "Cocos Islands"
        , country: "Cocos (Keeling) Islands"
        },
        { name: "America/Bogota"
        , city: "Bogotá"
        , country: "Colombia"
        },
        { name: "Indian/Comoro"
        , city: "Comoros"
        , country: "Comoros"
        },
        { name: "Pacific/Rarotonga"
        , city: "Rarotonga"
        , country: "Cook Islands"
        },
        { name: "America/Costa_Rica"
        , city: "Costa Rica"
        , country: "Costa Rica"
        },
        { name: "Africa/Abidjan"
        , city: "Abidjan"
        , country: "Côte d'Ivoire"
        },
        { name: "Europe/Zagreb"
        , city: "Zagreb"
        , country: "Croatia"
        },
        { name: "America/Havana"
        , city: "Havana"
        , country: "Cuba"
        },
        { name: "America/Curacao"
        , city: "Curaçao"
        , country: "Curaçao"
        },
        { name: "Asia/Famagusta"
        , city: "Famagusta"
        , country: "Cyprus"
        },
        { name: "Asia/Nicosia"
        , city: "Nicosia"
        , country: "Cyprus"
        },
        { name: "Europe/Prague"
        , city: "Prague"
        , country: "Czechia"
        },
        { name: "Africa/Kinshasa"
        , city: "Kinshasa"
        , country: "Democratic Republic of the Congo"
        },
        { name: "Africa/Lubumbashi"
        , city: "Lubumbashi"
        , country: "Democratic Republic of the Congo"
        },
        { name: "Europe/Copenhagen"
        , city: "Copenhagen"
        , country: "Denmark"
        },
        { name: "Africa/Djibouti"
        , city: "Djibouti"
        , country: "Djibouti"
        },
        { name: "America/Dominica"
        , city: "Dominica"
        , country: "Dominica"
        },
        { name: "America/Santo_Domingo"
        , city: "Santo Domingo"
        , country: "Dominican Republic"
        },
        { name: "Pacific/Galapagos"
        , city: "Galápagos Islands"
        , country: "Ecuador"
        },
        { name: "America/Guayaquil"
        , city: "Guayaquil"
        , country: "Ecuador"
        },
        { name: "Africa/Cairo"
        , city: "Cairo"
        , country: "Egypt"
        },
        { name: "America/El_Salvador"
        , city: "El Salvador"
        , country: "El Salvador"
        },
        { name: "Africa/Malabo"
        , city: "Malabo"
        , country: "Equatorial Guinea"
        },
        { name: "Africa/Asmara"
        , city: "Asmara"
        , country: "Eritrea"
        },
        { name: "Europe/Tallinn"
        , city: "Tallinn"
        , country: "Estonia"
        },
        { name: "Africa/Mbabane"
        , city: "Mbabane"
        , country: "Eswatini"
        },
        { name: "Africa/Addis_Ababa"
        , city: "Addis Ababa"
        , country: "Ethiopia"
        },
        { name: "Atlantic/Stanley"
        , city: "Stanley"
        , country: "Falkland Islands"
        },
        { name: "Atlantic/Faroe"
        , city: "Faroe"
        , country: "Faroe Islands"
        },
        { name: "Pacific/Fiji"
        , city: "Fiji"
        , country: "Fiji"
        },
        { name: "Europe/Helsinki"
        , city: "Helsinki"
        , country: "Finland"
        },
        { name: "Europe/Paris"
        , city: "Paris"
        , country: "France"
        },
        { name: "America/Cayenne"
        , city: "Cayenne"
        , country: "French Guiana"
        },
        { name: "Pacific/Gambier"
        , city: "Gambier"
        , country: "French Polynesia"
        },
        { name: "Pacific/Marquesas"
        , city: "Marquesas Islands"
        , country: "French Polynesia"
        },
        { name: "Pacific/Tahiti"
        , city: "Tahiti"
        , country: "French Polynesia"
        },
        { name: "Indian/Kerguelen"
        , city: "Kerguelen Islands"
        , country: "French Southern Territories"
        },
        { name: "Africa/Libreville"
        , city: "Libreville"
        , country: "Gabon"
        },
        { name: "Africa/Banjul"
        , city: "Banjul"
        , country: "Gambia"
        },
        { name: "Asia/Tbilisi"
        , city: "Tbilisi"
        , country: "Georgia"
        },
        { name: "Europe/Berlin"
        , city: "Berlin"
        , country: "Germany"
        },
        { name: "Europe/Busingen"
        , city: "Büsingen"
        , country: "Germany"
        },
        { name: "Africa/Accra"
        , city: "Accra"
        , country: "Ghana"
        },
        { name: "Europe/Gibraltar"
        , city: "Gibraltar"
        , country: "Gibraltar"
        },
        { name: "Europe/Athens"
        , city: "Athens"
        , country: "Greece"
        },
        { name: "America/Danmarkshavn"
        , city: "Danmarkshavn"
        , country: "Greenland"
        },
        { name: "America/Scoresbysund"
        , city: "Ittoqqortoormiit"
        , country: "Greenland"
        },
        { name: "America/Nuuk"
        , city: "Nuuk"
        , country: "Greenland"
        },
        { name: "America/Thule"
        , city: "Thule"
        , country: "Greenland"
        },
        { name: "America/Grenada"
        , city: "Grenada"
        , country: "Grenada"
        },
        { name: "America/Guadeloupe"
        , city: "Guadeloupe"
        , country: "Guadeloupe"
        },
        { name: "Pacific/Guam"
        , city: "Guam"
        , country: "Guam"
        },
        { name: "America/Guatemala"
        , city: "Guatemala"
        , country: "Guatemala"
        },
        { name: "Europe/Guernsey"
        , city: "Guernsey"
        , country: "Guernsey"
        },
        { name: "Africa/Conakry"
        , city: "Conakry"
        , country: "Guinea"
        },
        { name: "Africa/Bissau"
        , city: "Bissau"
        , country: "Guinea-Bissau"
        },
        { name: "America/Guyana"
        , city: "Guyana"
        , country: "Guyana"
        },
        { name: "America/Port-au-Prince"
        , city: "Port-au-Prince"
        , country: "Haiti"
        },
        { name: "America/Tegucigalpa"
        , city: "Tegucigalpa"
        , country: "Honduras"
        },
        { name: "Asia/Hong_Kong"
        , city: "Hong Kong"
        , country: "Hong Kong"
        },
        { name: "Europe/Budapest"
        , city: "Budapest"
        , country: "Hungary"
        },
        { name: "Atlantic/Reykjavik"
        , city: "Reykjavik"
        , country: "Iceland"
        },
        { name: "Asia/Kolkata"
        , city: "Kolkata"
        , country: "India"
        },
        { name: "Asia/Jakarta"
        , city: "Jakarta"
        , country: "Indonesia"
        },
        { name: "Asia/Jayapura"
        , city: "Jayapura"
        , country: "Indonesia"
        },
        { name: "Asia/Makassar"
        , city: "Makassar"
        , country: "Indonesia"
        },
        { name: "Asia/Pontianak"
        , city: "Pontianak"
        , country: "Indonesia"
        },
        { name: "Asia/Tehran"
        , city: "Tehran"
        , country: "Iran"
        },
        { name: "Asia/Baghdad"
        , city: "Baghdad"
        , country: "Iraq"
        },
        { name: "Europe/Dublin"
        , city: "Dublin"
        , country: "Ireland"
        },
        { name: "Europe/Isle_of_Man"
        , city: "Isle of Man"
        , country: "Isle of Man"
        },
        { name: "Asia/Jerusalem"
        , city: "Jerusalem"
        , country: "Israel"
        },
        { name: "Europe/Rome"
        , city: "Rome"
        , country: "Italy"
        },
        { name: "America/Jamaica"
        , city: "Jamaica"
        , country: "Jamaica"
        },
        { name: "Asia/Tokyo"
        , city: "Tokyo"
        , country: "Japan"
        },
        { name: "Europe/Jersey"
        , city: "Jersey"
        , country: "Jersey"
        },
        { name: "Asia/Amman"
        , city: "Amman"
        , country: "Jordan"
        },
        { name: "Asia/Aqtau"
        , city: "Aktau"
        , country: "Kazakhstan"
        },
        { name: "Asia/Almaty"
        , city: "Almaty"
        , country: "Kazakhstan"
        },
        { name: "Asia/Aqtobe"
        , city: "Aqtobe"
        , country: "Kazakhstan"
        },
        { name: "Asia/Atyrau"
        , city: "Atyrau"
        , country: "Kazakhstan"
        },
        { name: "Asia/Qostanay"
        , city: "Kostanay"
        , country: "Kazakhstan"
        },
        { name: "Asia/Qyzylorda"
        , city: "Kyzylorda"
        , country: "Kazakhstan"
        },
        { name: "Asia/Oral"
        , city: "Oral"
        , country: "Kazakhstan"
        },
        { name: "Africa/Nairobi"
        , city: "Nairobi"
        , country: "Kenya"
        },
        { name: "Pacific/Kanton"
        , city: "Kanton"
        , country: "Kiribati"
        },
        { name: "Pacific/Kiritimati"
        , city: "Kiritimati"
        , country: "Kiribati"
        },
        { name: "Pacific/Tarawa"
        , city: "Tarawa"
        , country: "Kiribati"
        },
        { name: "Asia/Kuwait"
        , city: "Kuwait"
        , country: "Kuwait"
        },
        { name: "Asia/Bishkek"
        , city: "Bishkek"
        , country: "Kyrgyzstan"
        },
        { name: "Asia/Vientiane"
        , city: "Vientiane"
        , country: "Laos"
        },
        { name: "Europe/Riga"
        , city: "Riga"
        , country: "Latvia"
        },
        { name: "Asia/Beirut"
        , city: "Beirut"
        , country: "Lebanon"
        },
        { name: "Africa/Maseru"
        , city: "Maseru"
        , country: "Lesotho"
        },
        { name: "Africa/Monrovia"
        , city: "Monrovia"
        , country: "Liberia"
        },
        { name: "Africa/Tripoli"
        , city: "Tripoli"
        , country: "Libya"
        },
        { name: "Europe/Vaduz"
        , city: "Vaduz"
        , country: "Liechtenstein"
        },
        { name: "Europe/Vilnius"
        , city: "Vilnius"
        , country: "Lithuania"
        },
        { name: "Europe/Luxembourg"
        , city: "Luxembourg"
        , country: "Luxembourg"
        },
        { name: "Asia/Macau"
        , city: "Macao"
        , country: "Macau"
        },
        { name: "Indian/Antananarivo"
        , city: "Antananarivo"
        , country: "Madagascar"
        },
        { name: "Africa/Blantyre"
        , city: "Blantyre"
        , country: "Malawi"
        },
        { name: "Asia/Kuala_Lumpur"
        , city: "Kuala Lumpur"
        , country: "Malaysia"
        },
        { name: "Asia/Kuching"
        , city: "Kuching"
        , country: "Malaysia"
        },
        { name: "Indian/Maldives"
        , city: "Maldives"
        , country: "Maldives"
        },
        { name: "Africa/Bamako"
        , city: "Bamako"
        , country: "Mali"
        },
        { name: "Europe/Malta"
        , city: "Malta"
        , country: "Malta"
        },
        { name: "Pacific/Kwajalein"
        , city: "Kwajalein Atoll"
        , country: "Marshall Islands"
        },
        { name: "Pacific/Majuro"
        , city: "Majuro"
        , country: "Marshall Islands"
        },
        { name: "America/Martinique"
        , city: "Martinique"
        , country: "Martinique"
        },
        { name: "Africa/Nouakchott"
        , city: "Nouakchott"
        , country: "Mauritania"
        },
        { name: "Indian/Mauritius"
        , city: "Mauritius"
        , country: "Mauritius"
        },
        { name: "Indian/Mayotte"
        , city: "Mayotte"
        , country: "Mayotte"
        },
        { name: "America/Bahia_Banderas"
        , city: "Bahía de Banderas"
        , country: "Mexico"
        },
        { name: "America/Cancun"
        , city: "Cancún"
        , country: "Mexico"
        },
        { name: "America/Chihuahua"
        , city: "Chihuahua"
        , country: "Mexico"
        },
        { name: "America/Ciudad_Juarez"
        , city: "Ciudad Juárez"
        , country: "Mexico"
        },
        { name: "America/Hermosillo"
        , city: "Hermosillo"
        , country: "Mexico"
        },
        { name: "America/Matamoros"
        , city: "Matamoros"
        , country: "Mexico"
        },
        { name: "America/Mazatlan"
        , city: "Mazatlán"
        , country: "Mexico"
        },
        { name: "America/Merida"
        , city: "Mérida"
        , country: "Mexico"
        },
        { name: "America/Mexico_City"
        , city: "Mexico City"
        , country: "Mexico"
        },
        { name: "America/Monterrey"
        , city: "Monterrey"
        , country: "Mexico"
        },
        { name: "America/Ojinaga"
        , city: "Ojinaga"
        , country: "Mexico"
        },
        { name: "America/Tijuana"
        , city: "Tijuana"
        , country: "Mexico"
        },
        { name: "Pacific/Chuuk"
        , city: "Chuuk"
        , country: "Micronesia"
        },
        { name: "Pacific/Kosrae"
        , city: "Kosrae"
        , country: "Micronesia"
        },
        { name: "Pacific/Pohnpei"
        , city: "Pohnpei"
        , country: "Micronesia"
        },
        { name: "Europe/Chisinau"
        , city: "Chișinău"
        , country: "Moldova"
        },
        { name: "Europe/Monaco"
        , city: "Monaco"
        , country: "Monaco"
        },
        { name: "Asia/Hovd"
        , city: "Khovd"
        , country: "Mongolia"
        },
        { name: "Asia/Ulaanbaatar"
        , city: "Ulaanbaatar"
        , country: "Mongolia"
        },
        { name: "Europe/Podgorica"
        , city: "Podgorica"
        , country: "Montenegro"
        },
        { name: "America/Montserrat"
        , city: "Montserrat"
        , country: "Montserrat"
        },
        { name: "Africa/Casablanca"
        , city: "Casablanca"
        , country: "Morocco"
        },
        { name: "Africa/Maputo"
        , city: "Maputo"
        , country: "Mozambique"
        },
        { name: "Asia/Yangon"
        , city: "Yangon"
        , country: "Myanmar"
        },
        { name: "Africa/Windhoek"
        , city: "Windhoek"
        , country: "Namibia"
        },
        { name: "Pacific/Nauru"
        , city: "Nauru"
        , country: "Nauru"
        },
        { name: "Asia/Kathmandu"
        , city: "Kathmandu"
        , country: "Nepal"
        },
        { name: "Europe/Amsterdam"
        , city: "Amsterdam"
        , country: "Netherlands"
        },
        { name: "Pacific/Noumea"
        , city: "Nouméa"
        , country: "New Caledonia"
        },
        { name: "Pacific/Auckland"
        , city: "Auckland"
        , country: "New Zealand"
        },
        { name: "Pacific/Chatham"
        , city: "Chatham Islands"
        , country: "New Zealand"
        },
        { name: "America/Managua"
        , city: "Managua"
        , country: "Nicaragua"
        },
        { name: "Africa/Niamey"
        , city: "Niamey"
        , country: "Niger"
        },
        { name: "Africa/Lagos"
        , city: "Lagos"
        , country: "Nigeria"
        },
        { name: "Pacific/Niue"
        , city: "Niue"
        , country: "Niue"
        },
        { name: "Pacific/Norfolk"
        , city: "Norfolk Island"
        , country: "Norfolk Island"
        },
        { name: "Asia/Pyongyang"
        , city: "Pyongyang"
        , country: "North Korea"
        },
        { name: "Europe/Skopje"
        , city: "Skopje"
        , country: "North Macedonia"
        },
        { name: "Pacific/Saipan"
        , city: "Saipan"
        , country: "Northern Mariana Islands"
        },
        { name: "Europe/Oslo"
        , city: "Oslo"
        , country: "Norway"
        },
        { name: "Asia/Muscat"
        , city: "Muscat"
        , country: "Oman"
        },
        { name: "Asia/Karachi"
        , city: "Karachi"
        , country: "Pakistan"
        },
        { name: "Pacific/Palau"
        , city: "Palau"
        , country: "Palau"
        },
        { name: "Asia/Gaza"
        , city: "Gaza"
        , country: "Palestine"
        },
        { name: "Asia/Hebron"
        , city: "Hebron"
        , country: "Palestine"
        },
        { name: "America/Panama"
        , city: "Panama"
        , country: "Panama"
        },
        { name: "Pacific/Bougainville"
        , city: "Bougainville"
        , country: "Papua New Guinea"
        },
        { name: "Pacific/Port_Moresby"
        , city: "Port Moresby"
        , country: "Papua New Guinea"
        },
        { name: "America/Asuncion"
        , city: "Asunción"
        , country: "Paraguay"
        },
        { name: "America/Lima"
        , city: "Lima"
        , country: "Peru"
        },
        { name: "Asia/Manila"
        , city: "Manila"
        , country: "Philippines"
        },
        { name: "Pacific/Pitcairn"
        , city: "Pitcairn Islands"
        , country: "Pitcairn Islands"
        },
        { name: "Europe/Warsaw"
        , city: "Warsaw"
        , country: "Poland"
        },
        { name: "Atlantic/Azores"
        , city: "Azores"
        , country: "Portugal"
        },
        { name: "Europe/Lisbon"
        , city: "Lisbon"
        , country: "Portugal"
        },
        { name: "Atlantic/Madeira"
        , city: "Madeira"
        , country: "Portugal"
        },
        { name: "America/Puerto_Rico"
        , city: "Puerto Rico"
        , country: "Puerto Rico"
        },
        { name: "Asia/Qatar"
        , city: "Qatar"
        , country: "Qatar"
        },
        { name: "Africa/Brazzaville"
        , city: "Brazzaville"
        , country: "Republic of the Congo"
        },
        { name: "Indian/Reunion"
        , city: "Réunion"
        , country: "Réunion"
        },
        { name: "Europe/Bucharest"
        , city: "Bucharest"
        , country: "Romania"
        },
        { name: "Asia/Anadyr"
        , city: "Anadyr"
        , country: "Russia"
        },
        { name: "Europe/Astrakhan"
        , city: "Astrakhan"
        , country: "Russia"
        },
        { name: "Asia/Barnaul"
        , city: "Barnaul"
        , country: "Russia"
        },
        { name: "Asia/Chita"
        , city: "Chita"
        , country: "Russia"
        },
        { name: "Asia/Irkutsk"
        , city: "Irkutsk"
        , country: "Russia"
        },
        { name: "Europe/Kaliningrad"
        , city: "Kaliningrad"
        , country: "Russia"
        },
        { name: "Asia/Kamchatka"
        , city: "Kamchatka"
        , country: "Russia"
        },
        { name: "Asia/Khandyga"
        , city: "Khandyga"
        , country: "Russia"
        },
        { name: "Europe/Kirov"
        , city: "Kirov"
        , country: "Russia"
        },
        { name: "Asia/Krasnoyarsk"
        , city: "Krasnoyarsk"
        , country: "Russia"
        },
        { name: "Asia/Magadan"
        , city: "Magadan"
        , country: "Russia"
        },
        { name: "Europe/Moscow"
        , city: "Moscow"
        , country: "Russia"
        },
        { name: "Asia/Novokuznetsk"
        , city: "Novokuznetsk"
        , country: "Russia"
        },
        { name: "Asia/Novosibirsk"
        , city: "Novosibirsk"
        , country: "Russia"
        },
        { name: "Asia/Omsk"
        , city: "Omsk"
        , country: "Russia"
        },
        { name: "Asia/Sakhalin"
        , city: "Sakhalin"
        , country: "Russia"
        },
        { name: "Europe/Samara"
        , city: "Samara"
        , country: "Russia"
        },
        { name: "Europe/Saratov"
        , city: "Saratov"
        , country: "Russia"
        },
        { name: "Asia/Srednekolymsk"
        , city: "Srednekolymsk"
        , country: "Russia"
        },
        { name: "Asia/Tomsk"
        , city: "Tomsk"
        , country: "Russia"
        },
        { name: "Europe/Ulyanovsk"
        , city: "Ulyanovsk"
        , country: "Russia"
        },
        { name: "Asia/Ust-Nera"
        , city: "Ust-Nera"
        , country: "Russia"
        },
        { name: "Asia/Vladivostok"
        , city: "Vladivostok"
        , country: "Russia"
        },
        { name: "Europe/Volgograd"
        , city: "Volgograd"
        , country: "Russia"
        },
        { name: "Asia/Yakutsk"
        , city: "Yakutsk"
        , country: "Russia"
        },
        { name: "Asia/Yekaterinburg"
        , city: "Yekaterinburg"
        , country: "Russia"
        },
        { name: "Africa/Kigali"
        , city: "Kigali"
        , country: "Rwanda"
        },
        { name: "America/St_Barthelemy"
        , city: "St. Barthélemy"
        , country: "Saint Barthélemy"
        },
        { name: "Atlantic/St_Helena"
        , city: "St. Helena"
        , country: "Saint Helena"
        },
        { name: "America/St_Kitts"
        , city: "St. Kitts"
        , country: "Saint Kitts and Nevis"
        },
        { name: "America/St_Lucia"
        , city: "St. Lucia"
        , country: "Saint Lucia"
        },
        { name: "America/Marigot"
        , city: "Marigot"
        , country: "Saint Martin"
        },
        { name: "America/Miquelon"
        , city: "Saint-Pierre"
        , country: "Saint Pierre and Miquelon"
        },
        { name: "America/St_Vincent"
        , city: "St. Vincent"
        , country: "Saint Vincent and the Grenadines"
        },
        { name: "Pacific/Apia"
        , city: "Apia"
        , country: "Samoa"
        },
        { name: "Europe/San_Marino"
        , city: "San Marino"
        , country: "San Marino"
        },
        { name: "Africa/Sao_Tome"
        , city: "São Tomé"
        , country: "São Tomé and Príncipe"
        },
        { name: "Asia/Riyadh"
        , city: "Riyadh"
        , country: "Saudi Arabia"
        },
        { name: "Africa/Dakar"
        , city: "Dakar"
        , country: "Senegal"
        },
        { name: "Europe/Belgrade"
        , city: "Belgrade"
        , country: "Serbia"
        },
        { name: "Indian/Mahe"
        , city: "Mahé"
        , country: "Seychelles"
        },
        { name: "Africa/Freetown"
        , city: "Freetown"
        , country: "Sierra Leone"
        },
        { name: "Asia/Singapore"
        , city: "Singapore"
        , country: "Singapore"
        },
        { name: "America/Lower_Princes"
        , city: "Lower Prince’s Quarter"
        , country: "Sint Maarten"
        },
        { name: "Europe/Bratislava"
        , city: "Bratislava"
        , country: "Slovakia"
        },
        { name: "Europe/Ljubljana"
        , city: "Ljubljana"
        , country: "Slovenia"
        },
        { name: "Pacific/Guadalcanal"
        , city: "Guadalcanal"
        , country: "Solomon Islands"
        },
        { name: "Africa/Mogadishu"
        , city: "Mogadishu"
        , country: "Somalia"
        },
        { name: "Africa/Johannesburg"
        , city: "Johannesburg"
        , country: "South Africa"
        },
        { name: "Atlantic/South_Georgia"
        , city: "South Georgia"
        , country: "South Georgia and the South Sandwich Islands"
        },
        { name: "Asia/Seoul"
        , city: "Seoul"
        , country: "South Korea"
        },
        { name: "Africa/Juba"
        , city: "Juba"
        , country: "South Sudan"
        },
        { name: "Atlantic/Canary"
        , city: "Canaries"
        , country: "Spain"
        },
        { name: "Africa/Ceuta"
        , city: "Ceuta"
        , country: "Spain"
        },
        { name: "Europe/Madrid"
        , city: "Madrid"
        , country: "Spain"
        },
        { name: "Asia/Colombo"
        , city: "Colombo"
        , country: "Sri Lanka"
        },
        { name: "Africa/Khartoum"
        , city: "Khartoum"
        , country: "Sudan"
        },
        { name: "America/Paramaribo"
        , city: "Paramaribo"
        , country: "Suriname"
        },
        { name: "Arctic/Longyearbyen"
        , city: "Longyearbyen"
        , country: "Svalbard and Jan Mayen"
        },
        { name: "Europe/Stockholm"
        , city: "Stockholm"
        , country: "Sweden"
        },
        { name: "Europe/Zurich"
        , city: "Zurich"
        , country: "Switzerland"
        },
        { name: "Asia/Damascus"
        , city: "Damascus"
        , country: "Syria"
        },
        { name: "Asia/Taipei"
        , city: "Taipei"
        , country: "Taiwan"
        },
        { name: "Asia/Dushanbe"
        , city: "Dushanbe"
        , country: "Tajikistan"
        },
        { name: "Africa/Dar_es_Salaam"
        , city: "Dar es Salaam"
        , country: "Tanzania"
        },
        { name: "Asia/Bangkok"
        , city: "Bangkok"
        , country: "Thailand"
        },
        { name: "Asia/Dili"
        , city: "Dili"
        , country: "Timor-Leste"
        },
        { name: "Africa/Lome"
        , city: "Lomé"
        , country: "Togo"
        },
        { name: "Pacific/Fakaofo"
        , city: "Fakaofo"
        , country: "Tokelau"
        },
        { name: "Pacific/Tongatapu"
        , city: "Tongatapu"
        , country: "Tonga"
        },
        { name: "America/Port_of_Spain"
        , city: "Port of Spain"
        , country: "Trinidad and Tobago"
        },
        { name: "Africa/Tunis"
        , city: "Tunis"
        , country: "Tunisia"
        },
        { name: "Europe/Istanbul"
        , city: "Istanbul"
        , country: "Turkey"
        },
        { name: "Asia/Ashgabat"
        , city: "Ashgabat"
        , country: "Turkmenistan"
        },
        { name: "America/Grand_Turk"
        , city: "Grand Turk"
        , country: "Turks and Caicos Islands"
        },
        { name: "Pacific/Funafuti"
        , city: "Funafuti"
        , country: "Tuvalu"
        },
        { name: "Africa/Kampala"
        , city: "Kampala"
        , country: "Uganda"
        },
        { name: "Europe/Kyiv"
        , city: "Kyiv"
        , country: "Ukraine"
        },
        { name: "Europe/Simferopol"
        , city: "Simferopol"
        , country: "Ukraine"
        },
        { name: "Asia/Dubai"
        , city: "Dubai"
        , country: "United Arab Emirates"
        },
        { name: "Europe/London"
        , city: "London"
        , country: "United Kingdom"
        },
        { name: "America/Adak"
        , city: "Adak"
        , country: "United States"
        },
        { name: "America/Anchorage"
        , city: "Anchorage"
        , country: "United States"
        },
        { name: "America/North_Dakota/Beulah"
        , city: "Beulah, North Dakota"
        , country: "United States"
        },
        { name: "America/Boise"
        , city: "Boise"
        , country: "United States"
        },
        { name: "America/North_Dakota/Center"
        , city: "Center, North Dakota"
        , country: "United States"
        },
        { name: "America/Chicago"
        , city: "Chicago"
        , country: "United States"
        },
        { name: "America/Denver"
        , city: "Denver"
        , country: "United States"
        },
        { name: "America/Detroit"
        , city: "Detroit"
        , country: "United States"
        },
        { name: "Pacific/Honolulu"
        , city: "Honolulu"
        , country: "United States"
        },
        { name: "America/Indiana/Indianapolis"
        , city: "Indianapolis"
        , country: "United States"
        },
        { name: "America/Juneau"
        , city: "Juneau"
        , country: "United States"
        },
        { name: "America/Indiana/Knox"
        , city: "Knox, Indiana"
        , country: "United States"
        },
        { name: "America/Los_Angeles"
        , city: "Los Angeles"
        , country: "United States"
        },
        { name: "America/Kentucky/Louisville"
        , city: "Louisville"
        , country: "United States"
        },
        { name: "America/Indiana/Marengo"
        , city: "Marengo, Indiana"
        , country: "United States"
        },
        { name: "America/Menominee"
        , city: "Menominee"
        , country: "United States"
        },
        { name: "America/Metlakatla"
        , city: "Metlakatla"
        , country: "United States"
        },
        { name: "America/Kentucky/Monticello"
        , city: "Monticello, Kentucky"
        , country: "United States"
        },
        { name: "America/North_Dakota/New_Salem"
        , city: "New Salem, North Dakota"
        , country: "United States"
        },
        { name: "America/New_York"
        , city: "New York"
        , country: "United States"
        },
        { name: "America/Nome"
        , city: "Nome"
        , country: "United States"
        },
        { name: "America/Indiana/Petersburg"
        , city: "Petersburg, Indiana"
        , country: "United States"
        },
        { name: "America/Phoenix"
        , city: "Phoenix"
        , country: "United States"
        },
        { name: "America/Sitka"
        , city: "Sitka"
        , country: "United States"
        },
        { name: "America/Indiana/Tell_City"
        , city: "Tell City, Indiana"
        , country: "United States"
        },
        { name: "America/Indiana/Vevay"
        , city: "Vevay, Indiana"
        , country: "United States"
        },
        { name: "America/Indiana/Vincennes"
        , city: "Vincennes, Indiana"
        , country: "United States"
        },
        { name: "America/Indiana/Winamac"
        , city: "Winamac, Indiana"
        , country: "United States"
        },
        { name: "America/Yakutat"
        , city: "Yakutat"
        , country: "United States"
        },
        { name: "Pacific/Midway"
        , city: "Midway Atoll"
        , country: "United States Minor Outlying Islands"
        },
        { name: "Pacific/Wake"
        , city: "Wake Island"
        , country: "United States Minor Outlying Islands"
        },
        { name: "America/St_Thomas"
        , city: "St. Thomas"
        , country: "United States Virgin Islands"
        },
        { name: "America/Montevideo"
        , city: "Montevideo"
        , country: "Uruguay"
        },
        { name: "Asia/Samarkand"
        , city: "Samarkand"
        , country: "Uzbekistan"
        },
        { name: "Asia/Tashkent"
        , city: "Tashkent"
        , country: "Uzbekistan"
        },
        { name: "Pacific/Efate"
        , city: "Efate"
        , country: "Vanuatu"
        },
        { name: "Europe/Vatican"
        , city: "Vatican"
        , country: "Vatican City"
        },
        { name: "America/Caracas"
        , city: "Caracas"
        , country: "Venezuela"
        },
        { name: "Asia/Ho_Chi_Minh"
        , city: "Ho Chi Minh"
        , country: "Vietnam"
        },
        { name: "Pacific/Wallis"
        , city: "Wallis & Futuna"
        , country: "Wallis and Futuna"
        },
        { name: "Africa/El_Aaiun"
        , city: "El Aaiún"
        , country: "Western Sahara"
        },
        { name: "Asia/Aden"
        , city: "Aden"
        , country: "Yemen"
        },
        { name: "Africa/Lusaka"
        , city: "Lusaka"
        , country: "Zambia"
        },
        { name: "Africa/Harare"
        , city: "Harare"
        , country: "Zimbabwe"
        }
    ]
