insert into game (title, short_title, handle, description, platforms)
values (
    'Counter Strike: Global Offensive',
    'CS:GO',
    'csgo',
    array['Find CS:GO teammates for competitive, wingman, danger zone matches and more.']::varchar[],
    array['steam']::varchar[]
);

insert into field (game_id, ilk, label, key, icon, ordinal)
values
    ((select id from game where game.handle = 'csgo'), 'single', 'Competitive rank', 'competitive-rank', 'fas fa-medal', 1),
    ((select id from game where game.handle = 'csgo'), 'single', 'Wingman rank', 'wingman-rank', 'fas fa-medal', 2),
    ((select id from game where game.handle = 'csgo'), 'single', 'Danger Zone rank', 'danger-zone-rank', 'fas fa-medal', 3),
    ((select id from game where game.handle = 'csgo'), 'single', 'Faceit rank', 'faceit-rank', 'fas fa-medal', 4),
    ((select id from game where game.handle = 'csgo'), 'multi', 'Role', 'role', 'fas fa-bullseye', 5),
    ((select id from game where game.handle = 'csgo'), 'multi', 'Interest', 'interest', 'fas fa-crosshairs', 6);

insert into field_option (field_id, label, key, ordinal)
values
    ((select id from field where field.key = 'competitive-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Silver I', 'silver-i', 1),
    ((select id from field where field.key = 'competitive-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Silver II', 'silver-ii', 2),
    ((select id from field where field.key = 'competitive-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Silver III', 'silver-iii', 3),
    ((select id from field where field.key = 'competitive-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Silver IV', 'silver-iv', 4),
    ((select id from field where field.key = 'competitive-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Silver Elite', 'silver-elite', 5),
    ((select id from field where field.key = 'competitive-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Silver Elite Master', 'silver-elite-master', 6),
    ((select id from field where field.key = 'competitive-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Gold Nova I', 'gold-nova-i', 7),
    ((select id from field where field.key = 'competitive-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Gold Nova II', 'gold-nova-ii', 8),
    ((select id from field where field.key = 'competitive-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Gold Nova III', 'gold-nova-iii', 9),
    ((select id from field where field.key = 'competitive-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Gold Nova Master', 'gold-nova-master', 10),
    ((select id from field where field.key = 'competitive-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Master Guardian I', 'master-guardian-i', 11),
    ((select id from field where field.key = 'competitive-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Master Guardian II', 'master-guardian-ii', 12),
    ((select id from field where field.key = 'competitive-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Master Guardian Elite', 'master-guardian-elite', 13),
    ((select id from field where field.key = 'competitive-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Distinguished Master Guardian', 'distinguished-master-guardian', 14),
    ((select id from field where field.key = 'competitive-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Legendary Eagle', 'legendary-eagle', 15),
    ((select id from field where field.key = 'competitive-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Legendary Eagle Master', 'legendary-eagle-master', 16),
    ((select id from field where field.key = 'competitive-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Supreme Master First Class', 'supreme-master-first-class', 17),
    ((select id from field where field.key = 'competitive-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'The Global Elite', 'the-global-elite', 18),
    ((select id from field where field.key = 'wingman-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Silver I', 'silver-i', 1),
    ((select id from field where field.key = 'wingman-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Silver II', 'silver-ii', 2),
    ((select id from field where field.key = 'wingman-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Silver III', 'silver-iii', 3),
    ((select id from field where field.key = 'wingman-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Silver IV', 'silver-iv', 4),
    ((select id from field where field.key = 'wingman-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Silver Elite', 'silver-elite', 5),
    ((select id from field where field.key = 'wingman-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Silver Elite Master', 'silver-elite-master', 6),
    ((select id from field where field.key = 'wingman-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Gold Nova I', 'gold-nova-i', 7),
    ((select id from field where field.key = 'wingman-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Gold Nova II', 'gold-nova-ii', 8),
    ((select id from field where field.key = 'wingman-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Gold Nova III', 'gold-nova-iii', 9),
    ((select id from field where field.key = 'wingman-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Gold Nova Master', 'gold-nova-master', 10),
    ((select id from field where field.key = 'wingman-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Master Guardian I', 'master-guardian-i', 11),
    ((select id from field where field.key = 'wingman-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Master Guardian II', 'master-guardian-ii', 12),
    ((select id from field where field.key = 'wingman-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Master Guardian Elite', 'master-guardian-elite', 13),
    ((select id from field where field.key = 'wingman-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Distinguished Master Guardian', 'distinguished-master-guardian', 14),
    ((select id from field where field.key = 'wingman-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Legendary Eagle', 'legendary-eagle', 15),
    ((select id from field where field.key = 'wingman-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Legendary Eagle Master', 'legendary-eagle-master', 16),
    ((select id from field where field.key = 'wingman-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Supreme Master First Class', 'supreme-master-first-class', 17),
    ((select id from field where field.key = 'wingman-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'The Global Elite', 'the-global-elite', 18),
    ((select id from field where field.key = 'danger-zone-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Lab Rat I', 'lab-rat-i', 1),
    ((select id from field where field.key = 'danger-zone-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Lab Rat II', 'lab-rat-ii', 2),
    ((select id from field where field.key = 'danger-zone-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Sprinting Hare I', 'sprinting-hare-i', 3),
    ((select id from field where field.key = 'danger-zone-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Sprinting Hare II', 'sprinting-hare-ii', 4),
    ((select id from field where field.key = 'danger-zone-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Wild Scout I', 'wild-scout-i', 5),
    ((select id from field where field.key = 'danger-zone-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Wild Scout II', 'wild-scout-ii', 6),
    ((select id from field where field.key = 'danger-zone-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Wild Scout Elite', 'wild-scout-elite', 7),
    ((select id from field where field.key = 'danger-zone-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Hunter Fox I', 'hunter-fox-i', 8),
    ((select id from field where field.key = 'danger-zone-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Hunter Fox II', 'hunter-fox-ii', 9),
    ((select id from field where field.key = 'danger-zone-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Hunter Fox III', 'hunter-fox-iii', 10),
    ((select id from field where field.key = 'danger-zone-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Hunter Fox Elite', 'hunter-fox-elite', 11),
    ((select id from field where field.key = 'danger-zone-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Timber Wolf', 'timber-wolf', 12),
    ((select id from field where field.key = 'danger-zone-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Ember Wolf', 'ember-wolf', 13),
    ((select id from field where field.key = 'danger-zone-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Wildfire Wolf', 'wildfire-wolf', 14),
    ((select id from field where field.key = 'danger-zone-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'The Howling Alpha', 'the-howling-alpha', 15),
    ((select id from field where field.key = 'faceit-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), '1', '1', 1),
    ((select id from field where field.key = 'faceit-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), '2', '2', 2),
    ((select id from field where field.key = 'faceit-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), '3', '3', 3),
    ((select id from field where field.key = 'faceit-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), '4', '4', 4),
    ((select id from field where field.key = 'faceit-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), '5', '5', 5),
    ((select id from field where field.key = 'faceit-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), '6', '6', 6),
    ((select id from field where field.key = 'faceit-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), '7', '7', 7),
    ((select id from field where field.key = 'faceit-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), '8', '8', 8),
    ((select id from field where field.key = 'faceit-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), '9', '9', 9),
    ((select id from field where field.key = 'faceit-rank' and field.game_id = ((select id from game where game.handle = 'csgo'))), '10', '10', 10),
    ((select id from field where field.key = 'role' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Rifler', 'rifler', 1),
    ((select id from field where field.key = 'role' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'AWPer', 'awper', 2),
    ((select id from field where field.key = 'role' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Lurker', 'lurker', 3),
    ((select id from field where field.key = 'role' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Entry fragger', 'entry-fragger', 4),
    ((select id from field where field.key = 'role' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Supporter', 'supporter', 5),
    ((select id from field where field.key = 'role' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'In-game leader', 'in-game-leader', 6),
    ((select id from field where field.key = 'interest' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Competitive', 'competitive', 1),
    ((select id from field where field.key = 'interest' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Wingman', 'wingman', 2),
    ((select id from field where field.key = 'interest' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Casual', 'casual', 3),
    ((select id from field where field.key = 'interest' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Deathmatch', 'deathmatch', 4),
    ((select id from field where field.key = 'interest' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Wargames', 'wargames', 5),
    ((select id from field where field.key = 'interest' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Danger Zone', 'danger-zone', 6),
    ((select id from field where field.key = 'interest' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Faceit', 'faceit', 7),
    ((select id from field where field.key = 'interest' and field.game_id = ((select id from game where game.handle = 'csgo'))), 'Leagues/tournaments', 'leagues-tournaments', 8);

insert into tracker (game_id, platform, title, template)
values
    ((select id from game where game.handle = 'csgo'), 'steam', 'tracker.gg', 'https://tracker.gg/csgo/profile/steam/'),
    ((select id from game where game.handle = 'csgo'), 'steam', 'csstats.gg', 'https://csstats.gg/player/');
