version: "3.7"

services:
  caddy:
    image: caddy:2.5.1
    container_name: caddy
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /home/bklaric/team-tavern/Caddyfile:/etc/caddy/Caddyfile
      - /home/bklaric/team-tavern/dist-client:/srv
      - /home/bklaric/caddy-docker/data:/data
      - /home/bklaric/caddy-docker/config:/config

  postgres:
    image: postgres:14.4
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=bklaric
      - POSTGRES_PASSWORD=bklaric
      - POSTGRES_DB=team_tavern
    volumes:
      - /home/bklaric/postgres-docker:/var/lib/postgresql/data
