version: "3.7"

services:
  postgres:
    image: postgres:14.4
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    volumes:
      - /home/bklaric/postgres-docker:/var/lib/postgresql/data

  node:
    image: node:18.4
    container_name: node
    restart: unless-stopped
    command: node /root/team-tavern/dist-server/server.js
    env_file: .env
    volumes:
      - /home/bklaric/team-tavern:/root/team-tavern
    depends_on:
      - postgres

  rendertron:
    image: dockette/rendertron
    container_name: rendertron
    restart: unless-stopped
    depends_on:
      - node

  caddy:
    image: caddy:2.5.1
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/bklaric/team-tavern/Caddyfile:/etc/caddy/Caddyfile
      - /home/bklaric/team-tavern/dist-client:/srv
      - /home/bklaric/caddy-docker/data:/data
      - /home/bklaric/caddy-docker/config:/config
    depends_on:
      - node
      - rendertron
