module TeamTavern.Server.Infrastructure.Countries where

allCountries :: Array String
allCountries =
    [ "Afghanistan"
    , "Albania"
    , "Algeria"
    , "American Samoa"
    , "Andorra"
    , "Angola"
    , "Anguilla"
    , "Antigua and Barbuda"
    , "Argentina"
    , "Armenia"
    , "Aruba"
    , "Austria"
    , "Azerbaijan"
    , "Bahrein"
    , "Bangladesh"
    , "Barbados"
    , "Belarus"
    , "Belgium"
    , "Belize"
    , "Benin"
    , "Bermuda"
    , "Bhutan"
    , "Bolivia"
    , "Bonaire"
    , "Bosnia and Herzegovina"
    , "Botswana"
    , "British Virgin Islands"
    , "Brunei"
    , "Bulgaria"
    , "Burkina Faso"
    , "Burundi"
    , "Cabo Verde"
    , "Cambodia"
    , "Cameroon"
    , "Cayman Islands"
    , "Central African Republic"
    , "Chad"
    , "Chile"
    , "China"
    , "Colombia"
    , "Comoros"
    , "Cook Islands"
    , "Costa Rica"
    , "Croatia"
    , "Cuba"
    , "Curaçao"
    , "Cyprus"
    , "Czech Republic"
    , "Côte d'Ivoire"
    , "Democratic Republic of the Congo"
    , "Denmark"
    , "Djibouti"
    , "Dominica"
    , "Dominican Republic"
    , "Easter Island"
    , "Ecuador"
    , "Egypt"
    , "El Salvador"
    , "Equatorial Guinea"
    , "Eritrea"
    , "Estonia"
    , "Eswatini (Swaziland)"
    , "Ethiopia"
    , "Falkland Islands"
    , "Federated States of Micronesia"
    , "Fiji"
    , "Finland"
    , "France"
    , "French Guiana"
    , "French Polynesia"
    , "Gabon"
    , "Gambia"
    , "Georgia"
    , "Germany"
    , "Ghana"
    , "Greece"
    , "Grenada"
    , "Guatemala"
    , "Guinea"
    , "Guinea-Bissau"
    , "Guyana"
    , "Haiti"
    , "Hawaii"
    , "Honduras"
    , "Hong Kong"
    , "Hungary"
    , "India"
    , "Indonesia"
    , "Iran"
    , "Iraq"
    , "Ireland"
    , "Israel"
    , "Italy"
    , "Jamaica"
    , "Japan"
    , "Jordan"
    , "Kazakhstan"
    , "Kenya"
    , "Kiribati"
    , "Kosovo"
    , "Kuwait"
    , "Kyrgyzstan"
    , "Laos"
    , "Latvia"
    , "Lebanon"
    , "Lesotho"
    , "Liberia"
    , "Libya"
    , "Lichtenstein"
    , "Lithuania"
    , "Luxemburg"
    , "Macau"
    , "Madagascar"
    , "Malawi"
    , "Malaysia"
    , "Maldives"
    , "Mali"
    , "Marshall Islands"
    , "Mauritania"
    , "Mauritius"
    , "Mayotte"
    , "Moldova"
    , "Monaco"
    , "Mongolia"
    , "Montenegro"
    , "Montserrat"
    , "Morocco"
    , "Mozambique"
    , "Myanmar"
    , "Namibia"
    , "Nauru"
    , "Nepal"
    , "Netherlands"
    , "Nicaragua"
    , "Niger"
    , "Nigeria"
    , "Niue"
    , "Norfolk Island"
    , "North Korea"
    , "North Macedonia"
    , "Norway"
    , "Oman"
    , "Pakistan"
    , "Palau"
    , "Palestine"
    , "Panama"
    , "Papua New Guinea"
    , "Paraguay"
    , "Peru"
    , "Philippines"
    , "Pitcairn Islands"
    , "Poland"
    , "Portugal"
    , "Puerto Rico"
    , "Qatar"
    , "Republic of the Congo"
    , "Romania"
    , "Rotuma"
    , "Russia"
    , "Rwanda"
    , "Réunion"
    , "Saint Barthélemy"
    , "Saint Helena, Ascension and Tristan da Cunha"
    , "Saint Kitts and Nevis"
    , "Saint Lucia"
    , "Saint Martin"
    , "Saint Pierre and Miquelon"
    , "Saint Vincent and the Grenadines"
    , "Samoa"
    , "Saudi Arabia"
    , "Senegal"
    , "Serbia"
    , "Seychelles"
    , "Sierra Leone"
    , "Singapore"
    , "Sint Maarten"
    , "Slovakia"
    , "Slovenia"
    , "Solomon Islands"
    , "Somalia"
    , "South Africa"
    , "South Korea"
    , "South Sudan"
    , "Spain"
    , "Sri Lanka"
    , "Sudan"
    , "Suriname"
    , "Sweden"
    , "Switzerland"
    , "Syria"
    , "São Tomé and Príncipe"
    , "Taiwan"
    , "Tajikistan"
    , "Tanzania"
    , "Thailand"
    , "The Bahamas"
    , "Timor Leste"
    , "Togo"
    , "Tokelau"
    , "Tonga"
    , "Trinidad and Tobago"
    , "Tunisia"
    , "Turkey"
    , "Turkmenistan"
    , "Turks and Caicos Islands"
    , "Tuvalu"
    , "UAE"
    , "Uganda"
    , "Ukraine"
    , "United Kingdom"
    , "United States Virgin Islands"
    , "Uruguay"
    , "Uzbekistan"
    , "Vanuatu"
    , "Venezuela"
    , "Vietnam"
    , "Wallis and Futuna"
    , "Yemen"
    , "Zambia"
    , "Zimbabwe"
    ]
