create table region (name text not null, superregion_name text null);

insert into region (name, superregion_name) values ('Europe', null);
    insert into region (name, superregion_name) values ('West Europe', 'Europe');
        insert into region (name, superregion_name) values ('United Kingdom', 'West Europe');
        insert into region (name, superregion_name) values ('Ireland', 'West Europe');
        insert into region (name, superregion_name) values ('Portugal', 'West Europe');
        insert into region (name, superregion_name) values ('Spain', 'West Europe');
        insert into region (name, superregion_name) values ('France', 'West Europe');
        insert into region (name, superregion_name) values ('Andorra', 'West Europe');
        insert into region (name, superregion_name) values ('Monaco', 'West Europe');
        insert into region (name, superregion_name) values ('Netherlands', 'West Europe');
        insert into region (name, superregion_name) values ('Belgium', 'West Europe');
        insert into region (name, superregion_name) values ('Luxemburg', 'West Europe');
        insert into region (name, superregion_name) values ('Germany', 'West Europe');
        insert into region (name, superregion_name) values ('Austria', 'West Europe');
        insert into region (name, superregion_name) values ('Switzerland', 'West Europe');
        insert into region (name, superregion_name) values ('Lichtenstein', 'West Europe');
        insert into region (name, superregion_name) values ('Italy', 'West Europe');
    insert into region (name, superregion_name) values ('East Europe', 'Europe');
        insert into region (name, superregion_name) values ('Poland', 'East Europe');
        insert into region (name, superregion_name) values ('Czech Republic', 'East Europe');
        insert into region (name, superregion_name) values ('Slovakia', 'East Europe');
        insert into region (name, superregion_name) values ('Hungary', 'East Europe');
        insert into region (name, superregion_name) values ('Slovenia', 'East Europe');
        insert into region (name, superregion_name) values ('Croatia', 'East Europe');
        insert into region (name, superregion_name) values ('Bosnia and Herzegovina', 'East Europe');
        insert into region (name, superregion_name) values ('Serbia', 'East Europe');
        insert into region (name, superregion_name) values ('Montenegro', 'East Europe');
        insert into region (name, superregion_name) values ('Kosovo', 'East Europe');
        insert into region (name, superregion_name) values ('Albania', 'East Europe');
        insert into region (name, superregion_name) values ('Greece', 'East Europe');
        insert into region (name, superregion_name) values ('North Macedonia', 'East Europe');
        insert into region (name, superregion_name) values ('Bulgaria', 'East Europe');
        insert into region (name, superregion_name) values ('Romania', 'East Europe');
        insert into region (name, superregion_name) values ('Moldova', 'East Europe');
        insert into region (name, superregion_name) values ('Ukraine', 'East Europe');
        insert into region (name, superregion_name) values ('Belarus', 'East Europe');
        insert into region (name, superregion_name) values ('Russia', 'East Europe');
    insert into region (name, superregion_name) values ('North Europe', 'Europe');
        insert into region (name, superregion_name) values ('Denmark', 'North Europe');
        insert into region (name, superregion_name) values ('Sweden', 'North Europe');
        insert into region (name, superregion_name) values ('Norway', 'North Europe');
        insert into region (name, superregion_name) values ('Finland', 'North Europe');
        insert into region (name, superregion_name) values ('Estonia', 'North Europe');
        insert into region (name, superregion_name) values ('Latvia', 'North Europe');
        insert into region (name, superregion_name) values ('Lithuania', 'North Europe');
insert into region (name, superregion_name) values ('Asia', null);
    insert into region (name, superregion_name) values ('West Asia', 'Asia');
        insert into region (name, superregion_name) values ('Turkey', 'West Asia');
        insert into region (name, superregion_name) values ('Georgia', 'West Asia');
        insert into region (name, superregion_name) values ('Armenia', 'West Asia');
        insert into region (name, superregion_name) values ('Azerbaijan', 'West Asia');
        insert into region (name, superregion_name) values ('Iran', 'West Asia');
        insert into region (name, superregion_name) values ('Iraq', 'West Asia');
        insert into region (name, superregion_name) values ('Syria', 'West Asia');
        insert into region (name, superregion_name) values ('Cyprus', 'West Asia');
        insert into region (name, superregion_name) values ('Lebanon', 'West Asia');
        insert into region (name, superregion_name) values ('Israel', 'West Asia');
        insert into region (name, superregion_name) values ('Palestine', 'West Asia');
        insert into region (name, superregion_name) values ('Jordan', 'West Asia');
        insert into region (name, superregion_name) values ('Saudi Arabia', 'West Asia');
        insert into region (name, superregion_name) values ('Yemen', 'West Asia');
        insert into region (name, superregion_name) values ('Oman', 'West Asia');
        insert into region (name, superregion_name) values ('UAE', 'West Asia');
        insert into region (name, superregion_name) values ('Qatar', 'West Asia');
        insert into region (name, superregion_name) values ('Bahrein', 'West Asia');
        insert into region (name, superregion_name) values ('Kuwait', 'West Asia');
    insert into region (name, superregion_name) values ('Central Asia', 'Asia');
        insert into region (name, superregion_name) values ('Kazakhstan', 'Central Asia');
        insert into region (name, superregion_name) values ('Kyrgyzstan', 'Central Asia');
        insert into region (name, superregion_name) values ('Tajikistan', 'Central Asia');
        insert into region (name, superregion_name) values ('Turkmenistan', 'Central Asia');
        insert into region (name, superregion_name) values ('Uzbekistan', 'Central Asia');
    insert into region (name, superregion_name) values ('South Asia', 'Asia');
        insert into region (name, superregion_name) values ('Afghanistan', 'South Asia');
        insert into region (name, superregion_name) values ('Bangladesh', 'South Asia');
        insert into region (name, superregion_name) values ('Bhutan', 'South Asia');
        insert into region (name, superregion_name) values ('India', 'South Asia');
        insert into region (name, superregion_name) values ('Maldives', 'South Asia');
        insert into region (name, superregion_name) values ('Nepal', 'South Asia');
        insert into region (name, superregion_name) values ('Pakistan', 'South Asia');
        insert into region (name, superregion_name) values ('Sri Lanka', 'South Asia');
    insert into region (name, superregion_name) values ('Southeast Asia', 'Asia');
        insert into region (name, superregion_name) values ('Brunei', 'Southeast Asia');
        insert into region (name, superregion_name) values ('Cambodia', 'Southeast Asia');
        insert into region (name, superregion_name) values ('Indonesia', 'Southeast Asia');
        insert into region (name, superregion_name) values ('Laos', 'Southeast Asia');
        insert into region (name, superregion_name) values ('Malaysia', 'Southeast Asia');
        insert into region (name, superregion_name) values ('Myanmar', 'Southeast Asia');
        insert into region (name, superregion_name) values ('Philippines', 'Southeast Asia');
        insert into region (name, superregion_name) values ('Singapore', 'Southeast Asia');
        insert into region (name, superregion_name) values ('Thailand', 'Southeast Asia');
        insert into region (name, superregion_name) values ('Timor Leste', 'Southeast Asia');
        insert into region (name, superregion_name) values ('Vietnam', 'Southeast Asia');
    insert into region (name, superregion_name) values ('East Asia', 'Asia');
        insert into region (name, superregion_name) values ('China', 'East Asia');
        insert into region (name, superregion_name) values ('Japan', 'East Asia');
        insert into region (name, superregion_name) values ('Mongolia', 'East Asia');
        insert into region (name, superregion_name) values ('North Korea', 'East Asia');
        insert into region (name, superregion_name) values ('South Korea', 'East Asia');
        insert into region (name, superregion_name) values ('Taiwan', 'East Asia');
        insert into region (name, superregion_name) values ('Hong Kong', 'East Asia');
        insert into region (name, superregion_name) values ('Macau', 'East Asia');
    insert into region (name, superregion_name) values ('North Asia (Russia)', 'Asia');
insert into region (name, superregion_name) values ('Africa', null);
    insert into region (name, superregion_name) values ('East Africa', 'Africa');
        insert into region (name, superregion_name) values ('Burundi', 'East Africa');
        insert into region (name, superregion_name) values ('Comoros', 'East Africa');
        insert into region (name, superregion_name) values ('Djibouti', 'East Africa');
        insert into region (name, superregion_name) values ('Eritrea', 'East Africa');
        insert into region (name, superregion_name) values ('Ethiopia', 'East Africa');
        insert into region (name, superregion_name) values ('Kenya', 'East Africa');
        insert into region (name, superregion_name) values ('Madagascar', 'East Africa');
        insert into region (name, superregion_name) values ('Malawi', 'East Africa');
        insert into region (name, superregion_name) values ('Mauritius', 'East Africa');
        insert into region (name, superregion_name) values ('Mayotte', 'East Africa');
        insert into region (name, superregion_name) values ('Mozambique', 'East Africa');
        insert into region (name, superregion_name) values ('Réunion', 'East Africa');
        insert into region (name, superregion_name) values ('Rwanda', 'East Africa');
        insert into region (name, superregion_name) values ('Seychelles', 'East Africa');
        insert into region (name, superregion_name) values ('Somalia', 'East Africa');
        insert into region (name, superregion_name) values ('South Sudan', 'East Africa');
        insert into region (name, superregion_name) values ('Tanzania', 'East Africa');
        insert into region (name, superregion_name) values ('Uganda', 'East Africa');
        insert into region (name, superregion_name) values ('Zambia', 'East Africa');
        insert into region (name, superregion_name) values ('Zimbabwe', 'East Africa');
    insert into region (name, superregion_name) values ('Central Africa', 'Africa');
        insert into region (name, superregion_name) values ('Angola', 'Central Africa');
        insert into region (name, superregion_name) values ('Cameroon', 'Central Africa');
        insert into region (name, superregion_name) values ('Central African Republic', 'Central Africa');
        insert into region (name, superregion_name) values ('Chad', 'Central Africa');
        insert into region (name, superregion_name) values ('Democratic Republic of the Congo', 'Central Africa');
        insert into region (name, superregion_name) values ('Republic of the Congo', 'Central Africa');
        insert into region (name, superregion_name) values ('Equatorial Guinea', 'Central Africa');
        insert into region (name, superregion_name) values ('Gabon', 'Central Africa');
        insert into region (name, superregion_name) values ('São Tomé and Príncipe', 'Central Africa');
    insert into region (name, superregion_name) values ('North Africa', 'Africa');
        insert into region (name, superregion_name) values ('Algeria', 'North Africa');
        insert into region (name, superregion_name) values ('Egypt', 'North Africa');
        insert into region (name, superregion_name) values ('Libya', 'North Africa');
        insert into region (name, superregion_name) values ('Morocco', 'North Africa');
        insert into region (name, superregion_name) values ('Sudan', 'North Africa');
        insert into region (name, superregion_name) values ('Tunisia', 'North Africa');
    insert into region (name, superregion_name) values ('South Africa', 'Africa');
        insert into region (name, superregion_name) values ('Botswana', 'South Africa');
        insert into region (name, superregion_name) values ('Eswatini (Swaziland)', 'South Africa');
        insert into region (name, superregion_name) values ('Lesotho', 'South Africa');
        insert into region (name, superregion_name) values ('Namibia', 'South Africa');
        insert into region (name, superregion_name) values ('South Africa, Republic of', 'South Africa');
    insert into region (name, superregion_name) values ('West Africa', 'Africa');
        insert into region (name, superregion_name) values ('Benin', 'West Africa');
        insert into region (name, superregion_name) values ('Burkina Faso', 'West Africa');
        insert into region (name, superregion_name) values ('Cabo Verde', 'West Africa');
        insert into region (name, superregion_name) values ('Côte d''Ivoire', 'West Africa');
        insert into region (name, superregion_name) values ('Gambia', 'West Africa');
        insert into region (name, superregion_name) values ('Ghana', 'West Africa');
        insert into region (name, superregion_name) values ('Guinea', 'West Africa');
        insert into region (name, superregion_name) values ('Guinea-Bissau', 'West Africa');
        insert into region (name, superregion_name) values ('Liberia', 'West Africa');
        insert into region (name, superregion_name) values ('Mali', 'West Africa');
        insert into region (name, superregion_name) values ('Mauritania', 'West Africa');
        insert into region (name, superregion_name) values ('Niger', 'West Africa');
        insert into region (name, superregion_name) values ('Nigeria', 'West Africa');
        insert into region (name, superregion_name) values ('Saint Helena Ascension and Tristan da Cunha', 'West Africa');
        insert into region (name, superregion_name) values ('Senegal', 'West Africa');
        insert into region (name, superregion_name) values ('Sierra Leone', 'West Africa');
        insert into region (name, superregion_name) values ('Togo', 'West Africa');
insert into region (name, superregion_name) values ('Oceania', null);
    insert into region (name, superregion_name) values ('Australia', 'Oceania');
    insert into region (name, superregion_name) values ('New Zealand', 'Oceania');
    insert into region (name, superregion_name) values ('Melanesia', 'Oceania');
        insert into region (name, superregion_name) values ('Fiji', 'Melanesia');
        insert into region (name, superregion_name) values ('Papua New Guinea', 'Melanesia');
        insert into region (name, superregion_name) values ('Solomon Islands', 'Melanesia');
        insert into region (name, superregion_name) values ('Vanuatu', 'Melanesia');
    insert into region (name, superregion_name) values ('Micronesia', 'Oceania');
        insert into region (name, superregion_name) values ('Federated States of Micronesia', 'Micronesia');
        insert into region (name, superregion_name) values ('Kiribati', 'Micronesia');
        insert into region (name, superregion_name) values ('Marshall Islands', 'Micronesia');
        insert into region (name, superregion_name) values ('Nauru', 'Micronesia');
        insert into region (name, superregion_name) values ('Palau', 'Micronesia');
    insert into region (name, superregion_name) values ('Polynesia', 'Oceania');
        insert into region (name, superregion_name) values ('American Samoa', 'Polynesia');
        insert into region (name, superregion_name) values ('Cook Islands', 'Polynesia');
        insert into region (name, superregion_name) values ('Easter Island', 'Polynesia');
        insert into region (name, superregion_name) values ('French Polynesia', 'Polynesia');
        insert into region (name, superregion_name) values ('Hawaii', 'Polynesia');
        insert into region (name, superregion_name) values ('Niue', 'Polynesia');
        insert into region (name, superregion_name) values ('Norfolk Island', 'Polynesia');
        insert into region (name, superregion_name) values ('Pitcairn Islands', 'Polynesia');
        insert into region (name, superregion_name) values ('Samoa', 'Polynesia');
        insert into region (name, superregion_name) values ('Tokelau', 'Polynesia');
        insert into region (name, superregion_name) values ('Tonga', 'Polynesia');
        insert into region (name, superregion_name) values ('Tuvalu', 'Polynesia');
        insert into region (name, superregion_name) values ('Wallis and Futuna', 'Polynesia');
        insert into region (name, superregion_name) values ('Rotuma', 'Polynesia');
insert into region (name, superregion_name) values ('North America', null);
    insert into region (name, superregion_name) values ('Greenland', 'North America');
    insert into region (name, superregion_name) values ('Canada', 'North America');
    insert into region (name, superregion_name) values ('United States of America', 'North America');
    insert into region (name, superregion_name) values ('Mexico', 'North America');
    insert into region (name, superregion_name) values ('Central America', 'North America');
        insert into region (name, superregion_name) values ('Belize', 'Central America');
        insert into region (name, superregion_name) values ('Costa Rica', 'Central America');
        insert into region (name, superregion_name) values ('El Salvador', 'Central America');
        insert into region (name, superregion_name) values ('Guatemala', 'Central America');
        insert into region (name, superregion_name) values ('Honduras', 'Central America');
        insert into region (name, superregion_name) values ('Nicaragua', 'Central America');
        insert into region (name, superregion_name) values ('Panama', 'Central America');
    insert into region (name, superregion_name) values ('Caribbean', 'North America');
        insert into region (name, superregion_name) values ('Antigua and Barbuda', 'Caribbean');
        insert into region (name, superregion_name) values ('The Bahamas', 'Caribbean');
        insert into region (name, superregion_name) values ('Barbados', 'Caribbean');
        insert into region (name, superregion_name) values ('Cuba', 'Caribbean');
        insert into region (name, superregion_name) values ('Dominica', 'Caribbean');
        insert into region (name, superregion_name) values ('Dominican Republic', 'Caribbean');
        insert into region (name, superregion_name) values ('Grenada', 'Caribbean');
        insert into region (name, superregion_name) values ('Haiti', 'Caribbean');
        insert into region (name, superregion_name) values ('Jamaica', 'Caribbean');
        insert into region (name, superregion_name) values ('Saint Kitts and Nevis', 'Caribbean');
        insert into region (name, superregion_name) values ('Saint Lucia', 'Caribbean');
        insert into region (name, superregion_name) values ('Saint Vincent and the Grenadines', 'Caribbean');
        insert into region (name, superregion_name) values ('Trinidad and Tobago', 'Caribbean');
        insert into region (name, superregion_name) values ('Anguilla', 'Caribbean');
        insert into region (name, superregion_name) values ('Aruba', 'Caribbean');
        insert into region (name, superregion_name) values ('Bermuda', 'Caribbean');
        insert into region (name, superregion_name) values ('British Virgin Islands', 'Caribbean');
        insert into region (name, superregion_name) values ('Bonaire', 'Caribbean');
        insert into region (name, superregion_name) values ('Cayman Islands', 'Caribbean');
        insert into region (name, superregion_name) values ('Curaçao', 'Caribbean');
        insert into region (name, superregion_name) values ('Montserrat', 'Caribbean');
        insert into region (name, superregion_name) values ('Puerto Rico', 'Caribbean');
        insert into region (name, superregion_name) values ('Saint Barthélemy', 'Caribbean');
        insert into region (name, superregion_name) values ('Saint Martin', 'Caribbean');
        insert into region (name, superregion_name) values ('Sint Maarten', 'Caribbean');
        insert into region (name, superregion_name) values ('Turks and Caicos Islands', 'Caribbean');
        insert into region (name, superregion_name) values ('United States Virgin Islands', 'Caribbean');
insert into region (name, superregion_name) values ('South America', null);
    insert into region (name, superregion_name) values ('Brazil', 'South America');
    insert into region (name, superregion_name) values ('South South America', 'South America');
        insert into region (name, superregion_name) values ('Argentina', 'South South America');
        insert into region (name, superregion_name) values ('Chile', 'South South America');
        insert into region (name, superregion_name) values ('Uruguay', 'South South America');
        insert into region (name, superregion_name) values ('Paraguay', 'South South America');
        insert into region (name, superregion_name) values ('Falkland Islands', 'South South America');
    insert into region (name, superregion_name) values ('West South America', 'South America');
        insert into region (name, superregion_name) values ('Bolivia', 'West South America');
        insert into region (name, superregion_name) values ('Ecuador', 'West South America');
        insert into region (name, superregion_name) values ('Peru', 'West South America');
    insert into region (name, superregion_name) values ('North South America', 'South America');
        insert into region (name, superregion_name) values ('Colombia', 'North South America');
        insert into region (name, superregion_name) values ('Venezuela', 'North South America');
        insert into region (name, superregion_name) values ('Suriname', 'North South America');
        insert into region (name, superregion_name) values ('Guyana', 'North South America');
        insert into region (name, superregion_name) values ('French Guiana', 'North South America');
